# Generated by Django 5.0.14 on 2025-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_remove_message_plaintext_message_des_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='plaintext',
            field=models.TextField(default='No plaintext'),
        ),
        migrations.AlterField(
            model_name='message',
            name='des_key',
            field=models.BinaryField(),
        ),
    ]
