# Generated by Django 5.0.14 on 2025-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_message_plaintext_alter_message_des_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_cipher',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
